apiVersion: v1
kind: Template
metadata:
  name: pipeline-resources-template
  annotations:
    description: 'Template to create project specific Pipeline resources.'
objects:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: consumer-repo
  spec:
    type: git
    params:
    - name: url
      value: https://github.com/g1raffi/quarkus-techlab-data-consumer.git
    - name: revision
      value: tekton
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: consumer-image
  spec:
    type: image
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}/data-consumer:latest
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: producer-repo
  spec:
    type: git
    params:
    - name: url
      value: https://github.com/g1raffi/quarkus-techlab-data-producer.git
    - name: revision
      value: tekton
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: producer-image
  spec:
    type: image
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}/data-producer:latest
parameters:
- description: OpenShift Project Name
  name: PROJECT_NAME
  mandatory: true