apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: go-hello-world
  name: go-hello-world
spec:
  replicas: 1
  selector:
    app: go-hello-world
    deploymentconfig: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
        deploymentconfig: go-hello-world
    spec:
      containers:
      - image: 'go-hello-world:latest'
        imagePullPolicy: IfNotPresent
        name: go-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - go-hello-world
      from:
        kind: ImageStreamTag
        name: go-hello-world:latest
    type: ImageChange
  strategy:
    type: Rolling
