apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: go-hello-world
  name: go-hello-world
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: ammlab/private-go-hello-world
    name: latest
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
