apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: data-producer
    application: amm-techlab
  name: data-producer
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: appuio-spring-boot-ex
    application: amm-techlab
  name: openjdk-11
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: registry.access.redhat.com/ubi8/openjdk-11
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/openjdk-11
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source