apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: data-producer
    application: amm-techlab
  name: data-producer
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""