apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: appuio-spring-boot-ex
  name: appuio-spring-boot-ex
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: appuio-spring-boot-ex
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None