apiVersion: v1
kind: Service
metadata:
  name: quarkus-producer
  labels:
    application: quarkus-producer
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: quarkus-producer
  sessionAffinity: None
  type: ClusterIP